services:
  db:
    container_name: mariadb
    build:
        context: .
        dockerfile: ./db/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: dev
      MARIADB_ROOT_HOST: '%'
      MARIADB_DATABASE: devDB
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
  app:
    container_name: golangApp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    depends_on:
      - db
    command:
      - /bin/bash
volumes:
    db_data: